rootProject.name = "NasaAssignment"
include(":app")
include(":domain")
include(":data")
include(":shared")
include(":features")
include(":features:vehicle_list")
include(":navgraph")
include(":core")
include(":features:vehicle_detail")
